#!/bin/sh
#
# @name Inno VTOL mini electro
#
# @type Standard VTOL
# @class VTOL
#
# @maintainer Roman Fedorenko <r.fedorenko@innopolis.ru>
#
# @output MAIN1 motor 1
# @output MAIN2 motor 2
# @output MAIN3 motor 3
# @output MAIN4 motor 4
# @output MAIN5 Aileron
# @output MAIN6 Elevator
# @output MAIN7 Rudder
# @output MAIN8 Throttle
#

. ${R}etc/init.d/rc.vtol_defaults

param set-default PWM_AUX_DIS5 950

param set-default PWM_RATE 400

# MC
param set-default MC_ROLL_P 6
param set-default MC_ROLLRATE_P 0.12
param set-default MC_ROLLRATE_I 0.15
param set-default MC_ROLLRATE_D 0.002
param set-default MC_ROLLRATE_MAX 100
param set-default MC_ROLLRATE_FF 0
param set-default MC_RR_INT_LIM 0.1

param set-default MC_PITCH_P 6
param set-default MC_PITCHRATE_P 0.12
param set-default MC_PITCHRATE_I 0.15
param set-default MC_PITCHRATE_D 0.002
param set-default MC_PITCHRATE_MAX 100
param set-default MC_PITCHRATE_FF 0
param set-default MC_PR_INT_LIM 0.1

param set-default MC_YAW_P 2.8
param set-default MC_YAWRATE_P 0.22
param set-default MC_YAWRATE_I 0.02
param set-default MC_YAWRATE_D 0
param set-default MC_YR_INT_LIM 0.1
param set-default MC_YAWRATE_FF 0
param set-default MC_YAWRATE_MAX 40
param set-default MPC_YAWRAUTO_MAX 40

# FW
param set-default FW_AIRSPD_MAX 35
param set-default FW_AIRSPD_MIN 23
param set-default FW_AIRSPD_TRIM 25
param set-default FW_PSP_OFF 5
param set-default FW_P_LIM_MAX 20
param set-default FW_P_LIM_MIN -20
param set-default FW_P_RMAX_NEG 50
param set-default FW_P_RMAX_POS 50

param set-default FW_PR_FF 0.5
param set-default FW_PR_I 0.02
param set-default FW_PR_IMAX 0.4
param set-default FW_PR_P 0.08
param set-default FW_RR_FF 0.6
param set-default FW_RR_I 0.01
param set-default FW_RR_IMAX 0.2
param set-default FW_RR_P 0.05
param set-default FW_THR_CRUISE 0.75

# VT
param set-default VT_ARSP_BLEND 9
param set-default VT_ARSP_TRANS 25
param set-default VT_F_TRANS_THR 0.85
param set-default VT_B_DEC_MSS 1
param set-default VT_B_TRANS_DUR 10
param set-default VT_ELEV_MC_LOCK 0
param set-default VT_FWD_THRUST_SC 0
param set-default VT_F_TRANS_DUR 10
param set-default VT_TRANS_MIN_TM 7
param set-default VT_TRANS_TIMEOUT 12
param set-default VT_MC_REV_YAW -1

param set-default VT_MOT_ID 1234
param set-default VT_FW_MOT_OFFID 1234
param set-default VT_IDLE_PWM_MC 1080
param set-default VT_TYPE 2

# MPC
param set-default MPC_MAN_TILT_MAX 20
param set-default MPC_TILTMAX_AIR 20
param set-default MPC_ACC_HOR_MAX 4
param set-default MPC_VEL_MANUAL 7
param set-default MPC_XY_VEL_MAX 7
param set-default MPC_XY_CRUISE 7


# BATTERY
param set-default BAT_A_PER_V 157.89
param set-default BAT_V_DIV 21
param set-default BAT_N_CELLS 12
param set-default BAT_V_CHARGED 4.35
param set-default BAT_V_EMPTY 3.35
param set-default BAT_LOW_THR 0.3

# UAVCAN
param set-default UAVCAN_ENABLE 3
param set-default COM_ARM_CHK_ESCS 0

# CIRCUIT BREAKER
param set-default CBRK_IO_SAFETY 22027

#SENSORS PARAMS
param set-default EKF2_GPS_POS_X -0.6
param set-default EKF2_GPS_POS_Z -0.12
param set-default EKF2_RNG_AID 1
param set-default EKF2_RNG_A_HMAX 10
param set-default SENS_EN_SF1XX 5

#TELEMETRY
param set-default MAV_0_CONFIG 104
param set-default MAV_0_RATE 2880
param set-default MAV_1_CONFIG 102
param set-default MAV_1_MODE 7
param set-default MAV_1_RATE 2880
param set-default MAV_RADIO_ID 0
param set-default SER_TEL2_BAUD 57600

param set-default MAV_TYPE 22

set MIXER inno_vtol_AAERT
set PWM_OUT 1234

set OUTPUT_MODE uavcan_esc
set OUTPUT_AUX_DEV /dev/uavcan/esc
set MIXER_AUX pass
